apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestyudmyinsuranceapp-deployment
  labels:
    app:  casestyudmyinsuranceapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app:  casestyudmyinsuranceapp
  template:
    metadata:
      labels:
        app: myinsuranceapp
    spec:
      containers:
      - name: myinsuranceapp-deployment
        image: espinoza6006/csmyinsuranceapp:v1
        ports:
        - name: http
          containerPort: 5000