apiVersion: v1
kind: Service
metadata:
  name: casestyudmyinsuranceapp-service
  labels:
    app: casestyudmyinsuranceapp
spec:
  selector:
    app: casestyudmyinsuranceapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32163 #30000-32767
    protocol: TCP
    name: http