apiVersion: apps/v1
kind: Deployment
metadata:
  name: caseStudymyinsuranceapp-deployment-az
  labels:
    app: caseStudymyinsuranceapp-az
spec:
  replicas: 5
  selector:
    matchLabels:
      app: caseStudymyinsuranceapp-az
  template:
    metadata:
      labels:
        app: caseStudymyinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: caseStudymyinsuranceapp-deployment-az
        image:  finalcsux.azurecr.io/myinsuranceapp:v3
        ports:
        - name: http
          containerPort: 5000