apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestyudmyinsuranceapp-deployment-az
  labels:
    app: casestyudmyinsuranceapp-az
spec:
  replicas: 5
  selector:
    matchLabels:
      app: casestyudmyinsuranceapp-az
  template:
    metadata:
      labels:
        app: casestyudmyinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: casestyudmyinsuranceapp-deployment-az
        # image:  finalcsux.azurecr.io/myinsuranceapp:v3
        ports:
        - name: http
          containerPort: 5000