apiVersion: v1
kind: Service
metadata:
  name: casestyudmyinsuranceapp-service-az
  labels:
    app: casestyudmyinsuranceapp-az
spec:
  type: NodePort
  selector:
    app: casestyudmyinsuranceapp-az
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32410
    protocol: TCP    
    name: http